# config file for https://github.com/CodeGoy/upload.git

# server endpoint
endpoint=

# non TLS port
port=

# TLS port
tlsport=

# file destination path = /mnt/raid/Public/upload/
path=

# Serve TLS
# adding cert and key file locations enables encrypted traffic
# Required if this server is exposed to the internet

# TLS cert file
cert=

# TLS key file
key=

